/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
	extend: 'Ext.panel.Panel',

	height: 480,
	layout: {
		type: 'border'
	},
	closable: false,
	collapsed: false,

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [{
				xtype: 'panel',
				region: 'west',
				split: true,
				width: 150,
				layout: {
					type: 'accordion'
				},
				items: [{
					xtype: 'panel',
					collapsed: false,
					layout: {
						type: 'vbox'
					},
					title: 'Menu',
					items: [{
						xtype: 'label',
						/*text: 'Rendimiento anual',*/
						html: '<a>Rendimiento anual</a>',
						listeners: {
							click: {
								element: 'el',
								//bind to the underlying el property on the panel
								fn: function() {
									var win = Ext.create('MyApp.view.MyWindow');
									win.setVisible(true);
									win.show();

								}
							}
						}
					},
					{
						xtype: 'label',
						/*text: 'Sueldos - Gerentes',*/
						html: '<a>Sueldos - Gerentes</a>',
						listeners: {
							click: {
								element: 'el',
								//bind to the underlying el property on the panel
								fn: function() {
									var msgCt = Ext.query("#msg-div");
									console.log(msgCt);
									if (msgCt[0] == null) {
										msgCt[0] = Ext.DomHelper.insertFirst(document.body, {
											id: 'msg-div'
										}, true);
									}
									var m = Ext.DomHelper.append(msgCt[0], '<div class="msg"><h3>Pendiente</h3><p>No disponible en esta Version</p></div>', true); /*msgCt.hide();*/
									m.slideIn('t').ghost("t", {
										delay: 2000,
										remove: true
									});
								}
							}
						}
					}]
				},
				{
					xtype: 'panel',
					collapsed: true,
					title: 'Menu 2'
				},
				{
					xtype: 'panel',
					collapsed: true,
					title: 'Conozcanos'
				}]
			},
			{
				xtype: 'tabpanel',
				region: 'center',
				disabled: false,
				draggable: false,
				floating: false,
				bodyBorder: false,
				overlapHeader: false,
				activeTab: 0,
				items: [{
					xtype: 'panel',
					tbar: [{
						text: 'Refrescar',
						handler: function() {
							store1.loadData(generateData(12));
						}
					}],
					layout: {
						type: 'border'
					},
					title: 'Ingreso anual',
					items: [{
						id: 'chartCmp',
						xtype: 'chart',
						style: 'background:#fff',
						animate: true,
						shadow: true,
						store: window.store1,
						axes: [{
							type: 'Numeric',
							position: 'left',
							fields: ['data1'],
							label: {
								renderer: Ext.util.Format.numberRenderer('0,0')
							},
							title: '$ x 1000',
							grid: true,
							minimum: 0
						},
						{
							type: 'Category',
							position: 'bottom',
							fields: ['name'],
							title: 'Meses'
						}],
						series: [{
							type: 'column',
							axis: 'left',
							highlight: true,
							tips: {
								trackMouse: true,
								width: 140,
								height: 28,
								renderer: function(storeItem, item) {
									this.setTitle(storeItem.get('name') + ': ' + storeItem.get('data1') + ' $');
								}
							},
							label: {
								display: 'insideEnd',
								'text-anchor': 'middle',
								field: 'data1',
								renderer: Ext.util.Format.numberRenderer('0'),
								orientation: 'vertical',
								color: '#333'
							},
							xField: 'name',
							yField: 'data1'
						}]
					}]
				},
				{
					xtype: 'panel',
					layout: {
						type: 'border'
					},
					tbar: [{
						text: 'Refrescar',
						handler: function() {
							store1.loadData(generateData(12));
						}
					}],
					title: 'Proyeccion 2013',
					items: [{
						xtype: 'chart',
						style: 'background:#fff',
						animate: true,
						store: store1,
						shadow: true,
						theme: 'Category1',
						legend: {
							position: 'right'
						},
						axes: [{
							type: 'Numeric',
							minimum: 0,
							position: 'left',
							fields: ['data1', 'data2', 'data3'],
							title: '$ x 1000',
							minorTickSteps: 1,
							grid: {
								odd: {
									opacity: 1,
									fill: '#ddd',
									stroke: '#bbb',
									'stroke-width': 0.5
								}
							}
						},
						{
							type: 'Category',
							position: 'bottom',
							fields: ['name'],
							title: 'Meses'
						}],
						series: [{
							type: 'line',
							highlight: {
								size: 7,
								radius: 7
							},
							axis: 'left',
							xField: 'name',
							yField: 'data1',
							markerConfig: {
								type: 'cross',
								size: 4,
								radius: 4,
								'stroke-width': 0
							}
						},
						{
							type: 'line',
							highlight: {
								size: 7,
								radius: 7
							},
							axis: 'left',
							smooth: true,
							xField: 'name',
							yField: 'data2',
							markerConfig: {
								type: 'circle',
								size: 4,
								radius: 4,
								'stroke-width': 0
							}
						},
						{
							type: 'line',
							highlight: {
								size: 7,
								radius: 7
							},
							axis: 'left',
							smooth: true,
							fill: true,
							xField: 'name',
							yField: 'data3',
							markerConfig: {
								type: 'circle',
								size: 4,
								radius: 4,
								'stroke-width': 0
							}
						}]
					}]
				},
				{
					xtype: 'panel',
					tbar: [{
						text: 'Refrescar',
						handler: function() {
							store1.loadData(generateData(12));
						}
					}],
					layout: {
						type: 'border'
					},
					title: 'Cruce anual',
					items: [{
						id: 'chartCmp2',
						xtype: 'chart',
						style: 'background:#fff',
						theme: 'Category2',
						insetPadding: 20,
						animate: true,
						store: store1,
						legend: {
							position: 'right'
						},
						axes: [{
							type: 'Radial',
							position: 'radial',
							label: {
								display: true
							}
						}],
						series: [{
							showInLegend: true,
							type: 'radar',
							xField: 'name',
							yField: 'data1',
							style: {
								opacity: 0.4
							}
						},
						{
							showInLegend: true,
							type: 'radar',
							xField: 'name',
							yField: 'data2',
							style: {
								opacity: 0.4
							}
						},
						{
							showInLegend: true,
							type: 'radar',
							xField: 'name',
							yField: 'data3',
							style: {
								opacity: 0.4
							}
						}]
					}]
				},
				{
					xtype: 'panel',
					layout: {
						type: 'border'
					},
					tbar: [{
						text: 'Refrescar',
						handler: function() {
							store4.loadData(generateData(1));
						}
					}],
					title: 'Estado de avance',
					items: [{
						xtype: 'chart',
						style: 'background:#fff',
						id:'reloj',						
						animate: {
							easing: 'elasticIn',
							duration: 3000
						},
						store: store4,
						insetPadding: 25,
						flex: 1,
						
						axes: [{
							
							type: 'gauge',
							position: 'gauge',
							minimum: 0,
							maximum: 100,
							steps: 20,
							margin: -10
							}],
						series: [{
							tips: {
							trackMouse: true,
							width: 40,
							height: 28,
							renderer: function(storeItem, item) {
							/*	var axe=Ext.getCmp('reloj');
							*/
								this.setTitle(storeItem.get('data1') + ' %');
							}
						},
							type: 'gauge',
							field: 'data1',
							donut: 30,
							colorSet: ['#F49D10', '#ddd']
						}]
					}]
				}
				,{
					 xtype: 'gmappanel',
					 title:'Mapa',
					 mapOptions:
					 {
						 mapTypeId: google.maps.MapTypeId.ROADMAP
						 },
                    center: {
                        geoCodeAddr: 'lord cochrane 220, santiago, Chile',
                        marker: {title: 'House'}
                    },
                    markers: [{
                        lat: -33.4492362,
                        lng: -70.654778,
                        title: 'PROBLEMA\n Haga click para ver',
                        listeners: {
                            click: function(e){
                                /*Ext.Msg.alert('Aqui Mostrar la imagen');*/
								var win = Ext.create('MyApp.view.MyWindowImage');
									win.setVisible(true);
									win.show();
									/*var nyc = new google.maps.LatLng(40.715, -74.002);  
var london = new google.maps.LatLng(51.506, -0.119);  
var distancia = google.maps.geometry.spherical.computeHeading(nyc, london);
alert(distancia)*/

                            }
                        }
                    }
					/*,{
                       lat: -33.4492372,
                        lng: -70.654778,
                        title: 'Otra'
                    }*/
					]
				}
				]
			}]
		});

		me.callParent(arguments);
	}

});